# [[file:../../../../Readme.org::*Nomad][Nomad:2]]
---
nomad_config_path: "/etc/nomad.d"
nomad_data_path: "/opt/nomad"

nomad_user: nomad
nomad_group: nomad
nomad_datacenter: dc1

nomad_systemd_unit_path: "/etc/systemd/system"

nomad_node_name: "{{ inventory_hostname_short }}"

nomad_bind_address: "{{ hostvars[inventory_hostname]['ansible_'+ nomad_iface ]['ipv4']['address'] }}"
nomad_advertise_address: "{{ hostvars[inventory_hostname]['ansible_' + nomad_iface]['ipv4']['address'] }}"

nomad_consul_address: "localhost:8500"

nomad_bootstrap_expect: "{{ nomad_servers | count or 3 }}"
nomad_group_name: "nomad_instances"
# Nomad:2 ends here
