# [[file:../Readme.org::*Setup server with ansible][Setup server with ansible:4]]
---
- hosts: all
  remote_user: "root"
  roles:
    - role: roles/do_setup
  ignore_unreachable: true

- hosts: all
  remote_user: "{{ created_username }}"
  become: true
  roles:
    - role: roles/common
    - role: roles/headscale
# Setup server with ansible:4 ends here
